add_executable(WordleSFML main.cpp BeforeGameWnd.cpp BeforeGameWnd.h Button.cpp Button.h Game.cpp Game.h GuessGrid.cpp GuessGrid.h KeyboardWnd.cpp KeyboardWnd.h PostGameWnd.cpp PostGameWnd.h PuzzleLetter.cpp PuzzleLetter.h PuzzleWnd.cpp PuzzleWnd.h SFMLGame.cpp SFMLGame.h WndInterface.h request_to_server.cpp make_request.cpp file_name.cpp client_http.hpp)
add_executable(make_request_test make_request.cpp make_request_test.cpp file_name.cpp client_http.hpp)
add_executable(Button_test Button_test.cpp Button.cpp Button.h)
add_executable(PostGameWnd_test Button.cpp Button.h PostGameWnd_test.cpp PostGameWnd.cpp PostGameWnd.h)
add_executable(PuzzleLetter_test PuzzleLetter_test.cpp PuzzleLetter.cpp PuzzleLetter.h)
add_executable(SFMLGame_test SFMLGame_test.cpp BeforeGameWnd.cpp BeforeGameWnd.h Button.cpp Button.h Game.cpp Game.h GuessGrid.cpp GuessGrid.h KeyboardWnd.cpp KeyboardWnd.h PostGameWnd.cpp PostGameWnd.h PuzzleLetter.cpp PuzzleLetter.h PuzzleWnd.cpp PuzzleWnd.h SFMLGame.cpp SFMLGame.h WndInterface.h request_to_server.cpp make_request.cpp file_name.cpp client_http.hpp)
add_executable(GuessGrid_test PuzzleLetter.cpp PuzzleLetter.h GuessGrid_test.cpp GuessGrid.cpp GuessGrid.h request_to_server.cpp make_request.cpp file_name.cpp client_http.hpp)
add_executable(BeforeGameWnd_test BeforeGameWnd_test.cpp BeforeGameWnd.cpp Button.cpp Button.h BeforeGameWnd.h)
add_executable(KeyboardWnd_test KeyboardWnd_test.cpp KeyboardWnd.cpp Button.cpp Button.h KeyboardWnd.h)
add_executable(PuzzleWnd_test PuzzleWnd_test.cpp BeforeGameWnd.cpp BeforeGameWnd.h Button.cpp Button.h Game.cpp Game.h GuessGrid.cpp GuessGrid.h KeyboardWnd.cpp KeyboardWnd.h PostGameWnd.cpp PostGameWnd.h PuzzleLetter.cpp PuzzleLetter.h PuzzleWnd.cpp PuzzleWnd.h SFMLGame.cpp SFMLGame.h WndInterface.h request_to_server.cpp make_request.cpp file_name.cpp client_http.hpp)

target_link_libraries(WordleSFML sfml-graphics sfml-window sfml-system)

target_link_libraries(make_request_test doctest)
target_link_libraries(Button_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(PostGameWnd_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(PuzzleLetter_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(SFMLGame_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(GuessGrid_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(BeforeGameWnd_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(KeyboardWnd_test sfml-graphics sfml-window sfml-system doctest)
target_link_libraries(PuzzleWnd_test sfml-graphics sfml-window sfml-system doctest)

enable_testing()
add_test(NAME make_request_test COMMAND make_request_test --force-colors -d)
add_test(NAME Button_test COMMAND Button_test --force-colors -d)
add_test(NAME PostGameWnd_test COMMAND PostGameWnd_test --force-colors -d)
add_test(NAME PuzzleLetter_test COMMAND PuzzleLetter_test --force-colors -d)
add_test(NAME SFMLGame_test COMMAND SFMLGame_test --force-colors -d)
add_test(NAME GuessGrid_test COMMAND GuessGrid_test --force-colors -d)
add_test(NAME BeforeGameWnd_test COMMAND BeforeGameWnd_test --force-colors -d)
add_test(NAME KeyboardWnd_test COMMAND KeyboardWnd_test --force-colors -d)
add_test(NAME PuzzleWnd_test COMMAND PuzzleWnd_test --force-colors -d)

